In [1]:
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np

In [12]:
project = pd.read_csv("C:/Users/Dell/Desktop/Dataset for Modelling.csv",sep=",")
project.head()

AccountNumber                                        AccountName  \
0   ACCT0000005                                   WagerWorks, Inc.   
1   ACCT0000006                                           OUHSC IT   
2   ACCT0000011                               Allstate Corporation   
3   ACCT0000026                                Clark County Nevada   
4   ACCT0000029  AAA Northern California, Nevada & Utah Insuran...   

   CompleteCustomerChurn  CustomerAgeCategoryIndicator  \
0                      1                      1.000000   
1                      0                      1.000000   
2                      0                      0.666667   
3                      0                      1.000000   
4                      0                      0.666667   

   AcctPaymentStatusIndicator  RepChangesinLast002Months_SUM  \
0                           1                            0.2   
1                           1                            0.4   
2                           1                            0.0   
3                           1                            0.2   
4                           1                            0.2   

   NumberOfProductionInstances_SUM  OptyWonLast12Months_Percent_SUM  \
0                           0.0000                           0.0000   
1                           0.2857                           0.5000   
2                           0.0000                           0.2222   
3                           0.0000                           0.6666   
4                           0.0000                           1.0000   

   OverallEngagementSatisfactionIndicator_SUM  \
0                                         0.5   
1                                         0.0   
2                                         0.0   
3                                         0.0   
4                                         0.0   

   FulfillerPriceCategoryIndicator  KnowledgeEventAttendeeCount  \
0                              0.5                         0.04   
1                              0.0                         0.20   
2                              0.0                         0.24   
3                              0.5                         0.24   
4                              0.0                         0.20   

   TotalAdoptionPercent  LicensedAdoptionPercent  AdoptionCategoryIndicator  \
0              0.359997                 0.093836                       0.75   
1              0.481480                 0.092100                       1.00   
2              0.518510                 0.099185                       1.00   
3              0.444440                 0.085016                       0.75   
4              0.555550                 0.099628                       1.00   

   LicensingCategoryIndicator  ResponseRatePercent  \
0                    0.333333             0.272750   
1                    0.333333             0.272750   
2                    0.333333             0.345478   
3                    0.333333             0.272750   
4                    0.666667             0.272750   

   NPSSatisfactionIndicator_SUM  \
0                      0.176471   
1                      0.176471   
2                      0.176471   
3                      0.176471   
4                      0.176471   

   OverallSupportSurveySatisfactionIndicator_SUM  UsageRiskIndicator_SUM  \
0                                       0.294118                0.000000   
1                                       0.294118                0.083333   
2                                       0.294118                0.000000   
3                                       0.411765                0.000000   
4                                       0.529412                0.000000   

   TotalActivityCount_SUM  
0                0.144578  
1                0.851406  
2                0.242972  
3                0.549197  
4                0.491968

In [13]:
x = project.drop(["CompleteCustomerChurn","AccountName","AccountNumber"],axis=1)
y = project["CompleteCustomerChurn"]

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=.3,random_state=1)
from sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression()
logmodel.fit(x_train,y_train)

c:\users\dell\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [15]:
predictions = logmodel.predict(x_test)
predictions

from sklearn.metrics import classification_report
classification_report(y_test,predictions)
from sklearn.metrics import accuracy_score
accuracy_score(y_test,predictions)

0.9550561797752809

# Without split

In [24]:
# preparing model considering all the variables 
# for regression model

import numpy as np
import statsmodels.formula.api as sm

In [30]:
# Preparing model                  
ml = sm.logit('CompleteCustomerChurn~CustomerAgeCategoryIndicator+AcctPaymentStatusIndicator+RepChangesinLast002Months_SUM+NumberOfProductionInstances_SUM+OptyWonLast12Months_Percent_SUM+OverallEngagementSatisfactionIndicator_SUM+FulfillerPriceCategoryIndicator+KnowledgeEventAttendeeCount+TotalAdoptionPercent+LicensedAdoptionPercent+AdoptionCategoryIndicator+LicensingCategoryIndicator+ResponseRatePercent+NPSSatisfactionIndicator_SUM+OverallSupportSurveySatisfactionIndicator_SUM+UsageRiskIndicator_SUM+TotalActivityCount_SUM',data=project).fit() # regression model

         Current function value: 0.089883
         Iterations: 35


c:\users\dell\appdata\local\programs\python\python37-32\lib\site-packages\statsmodels\base\model.py:512: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  "Check mle_retvals", ConvergenceWarning)


In [31]:
ml.params

Intercept                                          9.868390
CustomerAgeCategoryIndicator                       2.925707
AcctPaymentStatusIndicator                        -2.552053
RepChangesinLast002Months_SUM                      0.935433
NumberOfProductionInstances_SUM                 -114.974240
OptyWonLast12Months_Percent_SUM                   -2.611308
OverallEngagementSatisfactionIndicator_SUM        -2.255083
FulfillerPriceCategoryIndicator                   -0.340964
KnowledgeEventAttendeeCount                      -11.169429
TotalAdoptionPercent                             -71.345168
LicensedAdoptionPercent                            1.241915
AdoptionCategoryIndicator                         29.464902
LicensingCategoryIndicator                         0.604822
ResponseRatePercent                               -1.489224
NPSSatisfactionIndicator_SUM                     -10.955355
OverallSupportSurveySatisfactionIndicator_SUM     -6.893228
UsageRiskIndicator_SUM                  

In [28]:
ml.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                              OLS Regression Results                             
=================================================================================
Dep. Variable:     CompleteCustomerChurn   R-squared:                       0.188
Model:                               OLS   Adj. R-squared:                  0.184
Method:                    Least Squares   F-statistic:                     48.21
Date:                   Wed, 04 Dec 2019   Prob (F-statistic):          4.93e-146
Time:                           13:26:58   Log-Likelihood:                 658.62
No. Observations:                   3558   AIC:                            -1281.
Df Residuals:                       3540   BIC:                            -1170.
Df Model:                             17                                         
Covariance Type:               nonrobust                                         
=================================================================================================================
                                                    coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------------------------------
Intercept                                         0.4968      0.048     10.267      0.000       0.402       0.592
CustomerAgeCategoryIndicator                      0.1295      0.011     11.513      0.000       0.107       0.152
AcctPaymentStatusIndicator                       -0.1551      0.046     -3.399      0.001      -0.245      -0.066
RepChangesinLast002Months_SUM                     0.0439      0.021      2.046      0.041       0.002       0.086
NumberOfProductionInstances_SUM                  -0.1802      0.089     -2.035      0.042      -0.354      -0.007
OptyWonLast12Months_Percent_SUM                  -0.1820      0.011    -15.915      0.000      -0.204      -0.160
OverallEngagementSatisfactionIndicator_SUM       -0.0338      0.019     -1.743      0.081      -0.072       0.004
FulfillerPriceCategoryIndicator                  -0.0100      0.010     -1.041      0.298      -0.029       0.009
KnowledgeEventAttendeeCount                      -0.1104      0.054     -2.061      0.039      -0.215      -0.005
TotalAdoptionPercent                             -0.6300      0.049    -12.959      0.000      -0.725      -0.535
LicensedAdoptionPercent                           0.0599      0.037      1.627      0.104      -0.012       0.132
AdoptionCategoryIndicator                         0.2409      0.018     13.655      0.000       0.206       0.275
LicensingCategoryIndicator                        0.0166      0.006      2.880      0.004       0.005       0.028
ResponseRatePercent                              -0.0623      0.020     -3.117      0.002      -0.101      -0.023
NPSSatisfactionIndicator_SUM                     -0.2563      0.047     -5.477      0.000      -0.348      -0.165
OverallSupportSurveySatisfactionIndicator_SUM    -0.1181      0.026     -4.500      0.000      -0.170      -0.067
UsageRiskIndicator_SUM                           -0.1091      0.021     -5.111      0.000      -0.151      -0.067
TotalActivityCount_SUM                           -0.0002      0.019     -0.013      0.989      -0.037       0.036
==============================================================================
Omnibus:                     2180.698   Durbin-Watson:                   2.016
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            18028.644
Skew:                           2.926   Prob(JB):                         0.00
Kurtosis:                      12.347   Cond. No.                         52.0
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [32]:
ml.pred_table()

array([[3341.,   30.],
       [  86.,  101.]])

In [33]:
accuracy1 = (3341+101)/(3341+30+86+101)
accuracy1

0.9673974142776841

### Removing parameters having greater P value

#### Removing fuller price category indicator

In [35]:
ml2= sm.logit('CompleteCustomerChurn~CustomerAgeCategoryIndicator+AcctPaymentStatusIndicator+RepChangesinLast002Months_SUM+NumberOfProductionInstances_SUM+OptyWonLast12Months_Percent_SUM+OverallEngagementSatisfactionIndicator_SUM+KnowledgeEventAttendeeCount+TotalAdoptionPercent+LicensedAdoptionPercent+AdoptionCategoryIndicator+LicensingCategoryIndicator+ResponseRatePercent+NPSSatisfactionIndicator_SUM+OverallSupportSurveySatisfactionIndicator_SUM+UsageRiskIndicator_SUM+TotalActivityCount_SUM',data=project).fit() 

         Current function value: 0.090039
         Iterations: 35


c:\users\dell\appdata\local\programs\python\python37-32\lib\site-packages\statsmodels\base\model.py:512: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  "Check mle_retvals", ConvergenceWarning)


In [36]:
ml2.params

Intercept                                          9.689506
CustomerAgeCategoryIndicator                       2.916544
AcctPaymentStatusIndicator                        -2.565342
RepChangesinLast002Months_SUM                      0.921251
NumberOfProductionInstances_SUM                 -116.822891
OptyWonLast12Months_Percent_SUM                   -2.610947
OverallEngagementSatisfactionIndicator_SUM        -2.210966
KnowledgeEventAttendeeCount                      -11.069897
TotalAdoptionPercent                             -71.694860
LicensedAdoptionPercent                            1.189140
AdoptionCategoryIndicator                         29.613968
LicensingCategoryIndicator                         0.605393
ResponseRatePercent                               -1.545960
NPSSatisfactionIndicator_SUM                     -10.924498
OverallSupportSurveySatisfactionIndicator_SUM     -6.721465
UsageRiskIndicator_SUM                            -1.012020
TotalActivityCount_SUM                  

In [37]:
ml2.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                             Logit Regression Results                            
=================================================================================
Dep. Variable:     CompleteCustomerChurn   No. Observations:                 3558
Model:                             Logit   Df Residuals:                     3541
Method:                              MLE   Df Model:                           16
Date:                   Wed, 04 Dec 2019   Pseudo R-squ.:                  0.5629
Time:                           13:33:11   Log-Likelihood:                -320.36
converged:                         False   LL-Null:                       -732.87
Covariance Type:               nonrobust   LLR p-value:                2.898e-165
=================================================================================================================
                                                    coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------------------------------------
Intercept                                         9.6895      1.428      6.786      0.000       6.891      12.488
CustomerAgeCategoryIndicator                      2.9165      0.319      9.155      0.000       2.292       3.541
AcctPaymentStatusIndicator                       -2.5653      0.989     -2.595      0.009      -4.503      -0.627
RepChangesinLast002Months_SUM                     0.9213      0.621      1.484      0.138      -0.296       2.138
NumberOfProductionInstances_SUM                -116.8229   1.72e+04     -0.007      0.995   -3.38e+04    3.35e+04
OptyWonLast12Months_Percent_SUM                  -2.6109      0.289     -9.049      0.000      -3.176      -2.045
OverallEngagementSatisfactionIndicator_SUM       -2.2110      1.228     -1.801      0.072      -4.618       0.196
KnowledgeEventAttendeeCount                     -11.0699      4.048     -2.735      0.006     -19.004      -3.136
TotalAdoptionPercent                            -71.6949      8.016     -8.944      0.000     -87.405     -55.985
LicensedAdoptionPercent                           1.1891      1.043      1.140      0.254      -0.856       3.234
AdoptionCategoryIndicator                        29.6140      3.327      8.902      0.000      23.094      36.134
LicensingCategoryIndicator                        0.6054      0.093      6.504      0.000       0.423       0.788
ResponseRatePercent                              -1.5460      1.046     -1.478      0.139      -3.596       0.504
NPSSatisfactionIndicator_SUM                    -10.9245      2.862     -3.817      0.000     -16.534      -5.315
OverallSupportSurveySatisfactionIndicator_SUM    -6.7215      2.056     -3.268      0.001     -10.752      -2.691
UsageRiskIndicator_SUM                           -1.0120      0.772     -1.311      0.190      -2.525       0.501
TotalActivityCount_SUM                           -0.3812      0.442     -0.863      0.388      -1.247       0.484
=================================================================================================================

Possibly complete quasi-separation: A fraction 0.39 of observations can be
perfectly predicted. This might indicate that there is complete
quasi-separation. In this case some parameters will not be identified.
"""

In [38]:
ml2.pred_table()

array([[3341.,   30.],
       [  87.,  100.]])

In [39]:
accuracy2 = (3341+100)/(3341+30+87+100)
accuracy2

0.9671163575042159

### Removing Licensed adoption percent

In [40]:
ml3= sm.logit('CompleteCustomerChurn~CustomerAgeCategoryIndicator+AcctPaymentStatusIndicator+RepChangesinLast002Months_SUM+NumberOfProductionInstances_SUM+OptyWonLast12Months_Percent_SUM+OverallEngagementSatisfactionIndicator_SUM+KnowledgeEventAttendeeCount+TotalAdoptionPercent+AdoptionCategoryIndicator+LicensingCategoryIndicator+ResponseRatePercent+NPSSatisfactionIndicator_SUM+OverallSupportSurveySatisfactionIndicator_SUM+UsageRiskIndicator_SUM+TotalActivityCount_SUM',data=project).fit() 

         Current function value: 0.090180
         Iterations: 35


c:\users\dell\appdata\local\programs\python\python37-32\lib\site-packages\statsmodels\base\model.py:512: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  "Check mle_retvals", ConvergenceWarning)


In [41]:
ml3.pred_table()

array([[3342.,   29.],
       [  87.,  100.]])

In [46]:
accuracy3 = (3342+100)/(3342+29+87+100)
accuracy3

0.9673974142776841

### Removing TotalActivityCount_SUM

In [44]:
ml4= sm.logit('CompleteCustomerChurn~CustomerAgeCategoryIndicator+AcctPaymentStatusIndicator+RepChangesinLast002Months_SUM+NumberOfProductionInstances_SUM+OptyWonLast12Months_Percent_SUM+OverallEngagementSatisfactionIndicator_SUM+KnowledgeEventAttendeeCount+TotalAdoptionPercent+AdoptionCategoryIndicator+LicensingCategoryIndicator+ResponseRatePercent+NPSSatisfactionIndicator_SUM+OverallSupportSurveySatisfactionIndicator_SUM+UsageRiskIndicator_SUM',data=project).fit() 

         Current function value: 0.090305
         Iterations: 35


c:\users\dell\appdata\local\programs\python\python37-32\lib\site-packages\statsmodels\base\model.py:512: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  "Check mle_retvals", ConvergenceWarning)


In [45]:
ml4.pred_table()

array([[3341.,   30.],
       [  86.,  101.]])

In [47]:
accuracy4 = (3341+101)/(3341+30+86+101)
accuracy4

0.9673974142776841